### ISSUE TITLE
自绘光标的版本

### ISSUE THREAD

**Issue by BOKE2014** [red-axe/am-editor#174]
看到作者最近还在目前项目上不断的更新，请问未来自绘光标的版本是开一新项目吗？

**Comment by yanmao-cc** [comment]
是的，当前项目bug还是需要解决的，不做额外大功能开发。
新开项目以后也会提供当前项目的迁移方案------------------------------------------------------------------
***@***.***>
日　期：2022年05月26日 12:19:16
***@***.***>
***@***.***>
主　题：[red-axe/am-editor] 自绘光标的版本 (Issue #174)

看到作者最近还在目前项目上不断的更新，请问未来自绘光标的版本是开一新项目吗？

**Comment by BOKE2014** [comment]
> 
👌

**Comment by BOKE2014** [comment]
> 是的，当前项目bug还是需要解决的，不做额外大功能开发。 新开项目以后也会提供当前项目的迁移方案------------------------------------------------------------------ ***@***.***> 日　期：2022年05月26日 12:19:16 ***@***.***> ***@***.***> 主　题：[red-axe/am-editor] 自绘光标的版本 (Issue #174) 看到作者最近还在目前项目上不断的更新，请问未来自绘光标的版本是开一新项目吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

新的项目会全部包含目前的功能吗？是不是还会有新的功能在新的项目里出现呢？

**Comment by yanmao-cc** [comment]
会的


from 阿里邮箱 iPhone------------------------------------------------------------------
***@***.***>
日　期：2022年05月26日 12:34:41
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [red-axe/am-editor] 自绘光标的版本 (Issue #174)


是的，当前项目bug还是需要解决的，不做额外大功能开发。 新开项目以后也会提供当前项目的迁移方案------------------------------------------------------------------ @.> 日　期：2022年05月26日 12:19:16 @.> @.> 主　题：[red-axe/am-editor] 自绘光标的版本 (Issue #174) 看到作者最近还在目前项目上不断的更新，请问未来自绘光标的版本是开一新项目吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 
新的项目会全部包含目前的功能吗？是不是还会有新的功能在新的项目里出现呢？

**Comment by BOKE2014** [comment]
> 会的 from 阿里邮箱 iPhone------------------------------------------------------------------ ***@***.***> 日　期：2022年05月26日 12:34:41 ***@***.***> ***@***.***>; ***@***.***> 主　题：Re: [red-axe/am-editor] 自绘光标的版本 (Issue #174) 是的，当前项目bug还是需要解决的，不做额外大功能开发。 新开项目以后也会提供当前项目的迁移方案------------------------------------------------------------------ @.> 日　期：2022年05月26日 12:19:16 @.> @.> 主　题：[red-axe/am-editor] 自绘光标的版本 (Issue #174) 看到作者最近还在目前项目上不断的更新，请问未来自绘光标的版本是开一新项目吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 新的项目会全部包含目前的功能吗？是不是还会有新的功能在新的项目里出现呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

🐂
